### ISSUE TITLE
No horizontal scroll bar in main window

### ISSUE THREAD

**Issue by nemecky** [lukechadwick/Liquify#10]
Hi, maybe I'm missing something but in the main editor window I am not seeing a horizontal scroll bar. There's one in the left sidebar menu, but not in the main window? 

Here's a screenshot of the bottom of the page, you can see the scroll bar on the left but nothing in the main window. 
https://gyazo.com/1e30134a72b3ff8b2c0cac530f7b5739

Thanks!

**Comment by nemecky** [comment]
Just an update here. I actually do have the horizontal scroll at the bottom of the main window, but it only appears if I scroll all the way down to the end of the file. Once I scroll back up and the last line of code is no longer visible the scroll bar disappears.

**Comment by lukechadwick** [comment]
@nemecky this is the behaviour of the native editor, it may be possible to override this behaviour but it's not a bug of the extension.

**Comment by lukechadwick** [comment]
Fixed as in #11
