### ISSUE TITLE
No vertical scroll bar in main code window

### ISSUE THREAD

**Issue by TheMikeDub** [lukechadwick/Liquify#11]
First off I'd like to say thanks for making this extension Luke! So useful and much appreciated.

I am inconsistently seeing vertical scroll bars in the main code editor window, this appears to be happening regardless of if it's the old or 'new' editor on Shopify. They are there and function but I just can't see them all the time.
![Screenshot 2022-07-20 at 12 09 28](https://user-images.githubusercontent.com/10777972/179967928-00eb6d69-b017-4b8b-a751-c6b41da959b3.jpg)
.
The black line on the right is from my 2nd display.

**Comment by lukechadwick** [comment]
@TheMikeDub I can reproduce this on the old editor using the None/Light theme, the others have scrollbars for me. I don't have missing scrollbars on the new editor, I do have a missing horizontal scrollbar though which may be related. I'll look into it.

**Comment by TheMikeDub** [comment]
@lukechadwick Yeah, looks like you are correct. I can see the bars as you mentioned aswell as the lack of horizontal scroll.

**Comment by nemecky** [comment]
Yes I am missing a horizontal scroll bar in the main window, too. I created an issue for it but there's been no comments on it. For me this is really cumbersome especially since my keyboard doesn't have an End key and I have to use FN + > every time. Otherwise this extension is amazing and I'm thankful to have found it!

**Comment by lukechadwick** [comment]
@TheMikeDub @nemecky for me it looks like the new editor has been deployed to all stores, I tried about 10 and they are all on the new editor so I'm not sure I'll be able to fix the issue there.

For the missing horizontal scroll (unless at the bottom of the page), that's happening for me even if the extension is disabled entirely so is an issue with the Shopify editor.  On the new editor I don't do anything to the vanilla scrollbar behaviour.

**Comment by TheMikeDub** [comment]
@lukechadwick Yeah, I am seeing the new editor on most if not all the stores I use, thanks for looking into it though!

**Comment by lukechadwick** [comment]
@TheMikeDub I've added a fix to address the weird behaviour of the native editor. Both scrollbars should appear now, the update should take a day or so to roll out.
