### ISSUE TITLE
Add support for spanish language to Iframe Selector  

### ISSUE THREAD

**Issue by lsotoangeldonis** [lukechadwick/Liquify#14]
Hi I appreciate your work on your extension I would like to be able to use it on Shopify admin stores using Spanish as default language

As you can see the screenshot below the selector used on this cases is like the following: "Tienda online"

I have already made the change and would be able to send a pull request if you want to check it out

PS: I'm new to github contributions so let me now if anything else is need to be done to help.

![image](https://user-images.githubusercontent.com/38225539/181605868-0c42ddee-d561-471a-89bb-91fbdf3c1735.png)

**Comment by lukechadwick** [comment]
Hey thank you for raising this issue,

I'll get a fix out asap
