### ISSUE TITLE
Color Scheme + CMD+F Search Issues

### ISSUE THREAD

**Issue by NickReckless** [lukechadwick/Liquify#16]
Hello, originally downloaded this extension for its code editor themes, but all the additional bundled assets that it offers have ended up being extremely helpful.

However, the theme colors seemed to have changed for me recently. A lot of the code is very difficult to read without much contrast between the text and background. I really prefer working in dark mode but have been unable to for the past few days.

Additionally, the search function doesn't seem right. Whenever I CMD+F search, it opens the little search menu on top, and I can make my searches but it hides the highlighted search terms behind the search window, and when you try to click anywhere in the document or select any text, it jumps all over the place. The only way to stop it from jumping all over the place is if you remove the search term, which then removes the highlighted term you were looking for in the first place. 

I've tried this in an incognito environment to see if it's just a local issue or extension conflict, but it seems to be happening no matter what. I never made a post because I figured I was not the only one with these issues, but have not seen anything about it.

**Comment by lukechadwick** [comment]
Looks like they've updated the color classes with different names so I'll need to redo those. I can relocated the searchbox back to the bottom which will solve the problem of it overlaying the result, but I can't do much about the jumpy behaviour when clicking inside the editor

**Comment by NickReckless** [comment]
I appreciate you looking into it! As mentioned before, the extension itself has been extremely helpful, so thanks again!

**Comment by lukechadwick** [comment]
It looks like syntax highlighting is broken on all liquid files at the moment, not an extension issue, just an issue with the Shopify editor itself. Will need to wait for them to fix it first, not sure what their QA is doing atm lol

**Comment by NickReckless** [comment]
Hello Luke, It looks like the syntax highlighting seems to have made a return finally! Just wanted to let you know.

**Comment by lukechadwick** [comment]
Cheers, working on it now.

**Comment by lukechadwick** [comment]
@NickReckless update should be live now, may have to click update in your extension page

**Comment by NickReckless** [comment]
You the goat! @lukechadwick
