### ISSUE TITLE
File contents search function changed? Search bar disappears after every search

### ISSUE THREAD

**Issue by nemecky** [lukechadwick/Liquify#17]
Hi, it seems like the search function for file contents has started working differently than it used to. When I search for a term and click "next" it takes me to that term in the file but then the search bar disappears. If there's multiple instances of that word, all of the highlighting disappears. So I have to search again. 

Or if I click "all" it will highlight the words and then the search bar disappears. As soon as I click in the file contents all the found words lose their highlighting. 

Shouldn't the search bar be sticky and when clicking "next" it lets you jumps from word to word until you clear the search? And the same thing when clicking "all" - the search bar should stay there and all the words should remain highlighted until the search is closed? 

Or is this something on the Shopify side that they've done? 

Hopefully that all made sense, but let me know if you have any questions. Thanks!!

**Comment by lukechadwick** [comment]
I have noticed this also but if you disable the extension you'll see the behaviour is the same.  Seems we are all still beta testing the new editor
