### ISSUE TITLE
Chrome scroll on open search

### ISSUE THREAD

**Issue by casparjones** [lukechadwick/Liquify#22]
When I open the search in the editor and then click into it, the content scrolls away.
It looks like it is because the search bar is placed on top via the CSS (common.css):
`
.cm-scroller {
  order: 10 !important;
}
`

In the local copy I can remove the CSS command and the editor does not scroll away from the area you click into.

**Comment by lukechadwick** [comment]
@casparjones I've removed this.  The update should go out soon

**Comment by casparjones** [comment]
Vielen Dank, das hat den Fehler behoben. :-) 👍
