### ISSUE TITLE
Enhanced Search isn't functioning

### ISSUE THREAD

**Issue by calebmatthias** [lukechadwick/Liquify#25]
When attempting to search, I am not able to type in a query.  Is it possible there is something on my end interfering? 

Thanks

**Comment by lukechadwick** [comment]
Hi @calebmatthias 

Thanks for reporting, I can also see the issue, will look into it.

**Comment by lukechadwick** [comment]
@calebmatthias 

If you go to your stores theme link and add /assets.json, so something like shop.myshopify.com/admin/themes/123456789/assets.json

Can you see the asset list or does it prompt you to login?

**Comment by calebmatthias** [comment]
Hey Luke, thanks for your quick response. I am checking now

**Comment by calebmatthias** [comment]
I am able to pull it up @lukechadwick

**Comment by lukechadwick** [comment]
@calebmatthias hmm okay for me it displayed a login screen so the extension was pulling in HTML instead of JSON.  After logging in its working correctly, strange as I was already logged in but the assets.json link prompted to log in again.

Could you try a few things, in the theme that isn't working, check the console for any errors related to the extensions _search.js file?

Also see if the issue persists on a fresh Shopify theme like Dawn?

Thanks

**Comment by calebmatthias** [comment]
![1BABA1AA-4BF0-4186-8D12-E0B7DB84CB83](https://user-images.githubusercontent.com/88512148/192909760-67446025-6a4d-4d04-a9ca-a8dd6d41c1b1.jpeg)

**Comment by calebmatthias** [comment]
Works on Dawn, I wonder if it's the theme I am using that's causing the issue (District).

**Comment by lukechadwick** [comment]
@calebmatthias I've seen this before but haven't been able to recreate the issue as it's usually on other people's themes and they aren't able to send me a copy.

I suspect there's a weird character in the JSON of one of the files that causes this.

If you're able to duplicate your theme, strip out anything private and send me a zipped copy that would be ideal as I'd be able to recreate the issue on my end.

**Comment by calebmatthias** [comment]
[theme_export__bestinwellness-com-district__28SEP2022-0555pm.zip](https://github.com/lukechadwick/Liquify/files/9669841/theme_export__bestinwellness-com-district__28SEP2022-0555pm.zip)
Attached! I appreciate you going so in-depth!

**Comment by lukechadwick** [comment]
@calebmatthias It appears to be working on my store lol.  I'll try wrapping the code that is failing it a try-catch so it can spit out which file exactly is causing the issue and work around it.

Will upload 1.1.5 to to the chrome store now, once it's there it should output to the console which file is causing the issue.

**Comment by calebmatthias** [comment]
![F441CF17-5636-4917-AA04-5005856C376E_4_5005_c](https://user-images.githubusercontent.com/88512148/193080967-f688aa35-3cc4-4459-a854-d161806906c6.jpeg)

Thanks, here are the user messages

**Comment by lukechadwick** [comment]
@calebmatthias none of those are from the extension unfortunately. Is the search still not working? (orange magnifying glass spinning forever?)

**Comment by lukechadwick** [comment]
No response from reporter so closing this out.
