### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by kasperthefakecoder** [lukechadwick/Liquify#27]
Hey! Thank you for developing such an awesome extension.
I'm not sure why, but autocomplete is not working, and it's overlined in the extension window.
<img width="249" alt="Skærmbillede 2022-10-17 kl  10 14 56" src="https://user-images.githubusercontent.com/115980629/196124592-6bb08eaa-5cb4-4a76-801e-dacf6e0cb718.png">

**Comment by lukechadwick** [comment]
Hi @kasperthefakecoder 

This broke a while ago when Shopify released the new code editor, I'm not sure I'll be able to fix it as the CodeMirror editor is now hidden away in a closure and not externally accessible in JS like it used to be.  I'll have another look at it but if I can't fix it I'll remove the references to it from the app.

**Comment by lukechadwick** [comment]
Broken for now
