### ISSUE TITLE
New Shopify URL format

### ISSUE THREAD

**Issue by jcin30** [lukechadwick/Liquify#28]
Works on stores where code editor URL is still formatted:   https://store-name.myshopify.com/admin/themes/1234567890 

not the new format of:  https://admin.shopify.com/store/store-name/themes/1234567890

**Comment by jcin30** [comment]
From Shopify Support
We are consolidating Shopify’s admin domains into one domain – from [store-name].myshopify.com to admin.shopify.com/store/[store-name].

**Comment by astudioknowhere** [comment]
Yeah, looks like the new admin.myshopify change has broken things 😭

**Comment by lukechadwick** [comment]
Had to deal with some cross origin stuff now that the code editor is served from a different origin iframe but I've managed to get everything working.  Will upload the new version soon.

**Comment by astudioknowhere** [comment]
@lukechadwick Amazing! Thanks so much for fixing this so promptly, really saved my bacon as I rely on this extension so much 🙌
