### ISSUE TITLE
Enhanced Search not working

### ISSUE THREAD

**Issue by JhdChk** [lukechadwick/Liquify#31]
Hey Luke,

First of all thank you for your amazing extension! I wonder why Shopify doesn't integrate it in its code Editor by default..

I actually was really interested in the Enhanced Search tool as I'm always struggling to find specific elements in my code. However, I tried this feature but apparently it doesn't work. Maybe Shopify made an update recently? Would you be so kind to check out this issue? It would literally save my life 🙏

Many thanks for your help!

**Comment by lukechadwick** [comment]
Can you see any errors in the console from the _search.js file?

**Comment by JhdChk** [comment]
No I don't see any errors relating to the _search.js file

**Comment by lukechadwick** [comment]
Could you try the following settings to debug?

1. Go to the extensions page in Chrome and hit the update button, make sure you have the latest version (1.2.0 currently)
2. Try turning off your adblocker for the Shopify admin page you are working on. Some adblockers try to block some of the marketing/tracking related liquid files, which can cause issue. I did add some code to handle this in the latest release but only tried with uBlock.
3. Try use a fresh copy of the dawn theme, is there an issue there too?
4. Do the other features like theming work?
5. If none of the above works can you see any other issues reported in the browser console? The extension should output any errors there. Are you seeing the Enhanced search loading... with a spinning icon in the search field?

**Comment by JhdChk** [comment]
Hey Luke,

Thanks for these guidelines.

I did everything you said and the Enhanced Search is still not working. I can't see any errors in the console. I disabled my AdBlocker, used a Dawn theme and my theme, changed the code editor's theme, but still nothing. I can't see the spinning icon in the search field unfortunately.. Btw the autocomplete feature doesn't work for me too.

I have Chrome's Version 108.0.5359.124, do you think the problem comes from this version?

Thanks a lot for your help

**Comment by lukechadwick** [comment]
Your chrome version should be fine.  If the other features like theming the code editor aren't working it seems like the extension isn't loading at all. Are you on a *.myshopify.com url or an admin.shopify.com one?

**Comment by JhdChk** [comment]
No the theming code editor feature is working fine. The only 2 features that are not working are Enhanced search and Autocomplete. I'm on admin.shopify.com/*

**Comment by lukechadwick** [comment]
Have you had the extension long? I wonder if you need to reinstall it now that it needs permissions to access admin.shopify.com urls

**Comment by lukechadwick** [comment]
Autocomplete hasn't worked for a while so it looks like it's only search that isn't working for you.  If it's your store you could add me as a collaborator with themes access so I can have a look, otherwise I'm not sure there's much more I can do to debug without any console output.  Shopify usually does A/B testing on different stores so I can't always adapt to changes without being able to find a store that has the change.

**Comment by Rulluh** [comment]
How as this solved? My advanced search hasn't worked for a while. I re-installed, but I still cannot use advanced search to narrow down anything in the admin code editor anymore.
