### ISSUE TITLE
Editor font size is too small

### ISSUE THREAD

**Issue by onkar4058** [lukechadwick/Liquify#32]
@lukechadwick 

Thanks for wonderful chrome extension.
I only find one issue while using the extension. the editor font-size is fixed to 12px. which is too short and hard to see

I think this need to be update to much larger font-size.

Thanks

**Comment by lukechadwick** [comment]
Hi @onkar4058 

I'll look into adding a setting so you can choose the size.

**Comment by lukechadwick** [comment]
Resolved in https://github.com/lukechadwick/Liquify/pull/33. I've added a font size selector.

Should update across the chrome store soon.
