### ISSUE TITLE
Automatically remove from extension

### ISSUE THREAD

**Issue by VarunmehraRG** [lukechadwick/Liquify#34]
Automatically remove from extension and stop working. Why?

**Comment by lukechadwick** [comment]
Can you provide a bit more detail? I'm not sure what you're talking about.

**Comment by VarunmehraRG** [comment]
This extension always automatically gets removed from the Chrome browser after 10-15 minutes and stops working.

**Comment by lukechadwick** [comment]
@VarunmehraRG it's not possible for Chrome extensions to remove themselves from the browser so there isn't much I can do.  The only thing I can think of is that there's an issue with your Chrome account/extension sync, or you're on a work machine with some kind of group policy/extension whitelist.
