### ISSUE TITLE
Advanced Search Not Working After Load

### ISSUE THREAD

**Issue by Rulluh** [lukechadwick/Liquify#35]
After the gold search icon finishes spinning, attemping to use the search will result in no collapsing to the available pages and does not narrow down search results. I haven't seen solutions that work to fix this so far. When searching, I get this error in the console for every letter pressed.
![image](https://github.com/lukechadwick/Liquify/assets/41551566/e0b6a54d-bc29-4ea8-a90e-422bf8d9c665)

Thank you.

**Comment by lukechadwick** [comment]
@Rulluh thanks for reporting, I've been able to reproduce this on a theme so will come up with a fix.

**Comment by lukechadwick** [comment]
@Rulluh sorry for the delay. I've added a throttle option to the new version. It should address this issue by limiting the amount of requests per second to Shopify's asset API.
