### ISSUE TITLE
Search not working in Chrome / Brave

### ISSUE THREAD

**Issue by JMSHopify** [lukechadwick/Liquify#37]
Hey there, thanks for the amazing add-on.

I'm having trouble with the add-on not searching, but changing the ui to black. Here is a screenshot from Dawn 11.0
![image](https://github.com/lukechadwick/Liquify/assets/110251269/67df9bd9-2fca-4a7c-85dc-d8316091c38e)

The spinny search animation doesn't seem to be happening.

I also tried on the Modular theme in Brave and got the same result. I have tried uninstalling and reinstalling the add-on but get the same result. 

I had this happen a couple weeks ago and it seemed to resolve itself after I installed some other add-ons that claim to do the same thing (but yours works best).

Thanks!

**Comment by JMSHopify** [comment]
Ok I installed the EZFY code search and now yours works lol. 
![image](https://github.com/lukechadwick/Liquify/assets/110251269/b33cc2d8-8a13-430b-ad91-975a1ad59537)

**Comment by lukechadwick** [comment]
@JMSHopify can you see anything in the console when it fails?

**Comment by JMSHopify** [comment]
> 

Nothing when searching, but if I click the shortcuts I get errors.
[admin.shopify.com-1694027137961.log](https://github.com/lukechadwick/Liquify/files/12541480/admin.shopify.com-1694027137961.log)

**Comment by lukechadwick** [comment]
@JMSHopify  This should be resolved in the new version, try selecting a throttle that matches the stores plan.
