### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by metamocap** [lukechadwick/Liquify#38]
Not so much an issue, but rather a usage question / feature request.

Liquify is wonderful! 

Is there a way to customize the the colors it uses? Particularly the code highlight color, when selecting blocks of code (VSCode editor theme) makes the underlying code a bit hard for me to read. I realize I can click on the Liquify icon in the title bar of Chrome to darken the highlight, but that's an extra step and still doesn't handle the initial selection aspect as well as I might prefer.

![image](https://github.com/lukechadwick/Liquify/assets/38405797/3648433c-ba7f-4029-947f-2355bf655537)
when selecting

![image](https://github.com/lukechadwick/Liquify/assets/38405797/a7dad9ef-7581-4846-b727-d55d105cf18b)
after clicking on Liquify icon

Also... is there any way to enable word wrap?

**Comment by lukechadwick** [comment]
@metamocap I don't have any plans to add a color picker atm. I've fixed the color highlighting though.

Wordwrap used to be an option, but now Shopify makes it impossible to access the codemirror editor object to change the functionality.
