### ISSUE TITLE
Mac operating problems

### ISSUE THREAD

**Issue by dlopezros** [lukechadwick/Liquify#40]
For a few weeks the extension has not been working on MacBook Pro with macOS version 13.4 (22F66)

- Incorrect colors, makes some options/buttons not legible.
- code finder does not show the text, it is in dark color.
- Theme file finder not working

I attach screenshots:
<img width="756" alt="Screenshot at Nov 03 13-03-02" src="https://github.com/lukechadwick/Liquify/assets/1651078/08371d9c-6053-476c-8c88-655b467979f3">
<img width="366" alt="Screenshot at Nov 03 13-03-23" src="https://github.com/lukechadwick/Liquify/assets/1651078/eb6e8fa0-d662-4443-a2cc-70e36b7a101e">
<img width="749" alt="Screenshot at Nov 03 13-03-51" src="https://github.com/lukechadwick/Liquify/assets/1651078/e7842236-b64b-486f-af79-d2d44142408d">
<img width="750" alt="Screenshot at Nov 03 13-05-22" src="https://github.com/lukechadwick/Liquify/assets/1651078/d2aed647-e37b-4ae1-9b0f-d16beaa2b61f">
<img width="751" alt="Screenshot at Nov 03 13-02-29" src="https://github.com/lukechadwick/Liquify/assets/1651078/6a211f2b-3da9-41df-b700-2b7c94f77861">

**Comment by kayteetrudeau** [comment]
Just updated to Sonoma 14.1.2, file name and text field color issues persist:
![image](https://github.com/lukechadwick/Liquify/assets/38011525/791f41fa-e952-48ba-aeea-e892c25a2904)

**Comment by lukechadwick** [comment]
I've pushed out a new version @dlopezros @kayteetrudeau 

Please let me know if this resolves the issue

**Comment by dlopezros** [comment]
Hi @lukechadwick.
The color problem is solved!
The search engine still doesn't work.

<img width="615" alt="Screenshot at Dec 14 17-14-30" src="https://github.com/lukechadwick/Liquify/assets/1651078/c7e861fd-6de6-48df-96b1-05b4c854a6e7">

regards.

**Comment by lukechadwick** [comment]
Hi @dlopezros 

Could you please send me a screenshot of the dev console?

**Comment by refueledinc** [comment]
I too have the tab color issue. Chrome store only has up to version 1.4.3. How do I update to the latest version that has the fix?

**Comment by VitaliyKovalenko1** [comment]
<img width="326" alt="image" src="https://github.com/user-attachments/assets/1ca13912-0368-4630-94bf-fd1263ecdbf2">

I have again this problem in Google Chrome ( Version 128.0.6613.138 )

**Comment by kayteetrudeau** [comment]
I now have the same issue as @VitaliyKovalenko1 and am unable to type anything in the search bar. 

The color stuff otherwise is much better though!

**Comment by sp-hy** [comment]
Hey all, it looks like I need to make some updates to the extension.   I will try and get to it soon.

**Comment by VitaliyKovalenko1** [comment]
> I now have the same issue as @VitaliyKovalenko1 and am unable to type anything in the search bar.
> 
> The color stuff otherwise is much better though!

Hi there 
The problem is with input z-index elem

I have found it and have added styles locally every time)) 

<img width="630" alt="Screenshot 2024-09-24 at 10 45 29" src="https://github.com/user-attachments/assets/b6021868-f8d4-4dba-927b-0aa97145ef1a">
<img width="341" alt="Screenshot 2024-09-24 at 10 45 32" src="https://github.com/user-attachments/assets/7172e3d3-2f15-4766-bb64-68fc0e3078f7">

**Comment by sp-hy** [comment]
I've released a new version which should be available soon
