### ISSUE TITLE
Crash Chrome during use

### ISSUE THREAD

**Issue by onkar4058** [lukechadwick/Liquify#43]
After adding the new throttle limit extension now works weird on Chrome Windows 11.
After using it sometime after chrome hung and crashed frequently.

To test it disable all the extensions along with [Liquify](https://github.com/lukechadwick/Liquify) and works on the default code editor all day works well with no issue.

And then no other extension only [Liquify](https://github.com/lukechadwick/Liquify), this happens again.

No way to check console error, direct hang, and crash.

Note: Chrome and WIN 11 have latest versions.

Limit is set to 50 and getting this error into console

![image](https://github.com/lukechadwick/Liquify/assets/51198725/f42c0e94-2712-4bd1-905e-fd9cf6ce9119)

**Comment by lukechadwick** [comment]
@onkar4058 I identified some performance issues in the last version and have pushed out a new version (1.4.2), please try that and let me know if it resolves your issue.

**Comment by onkar4058** [comment]
@lukechadwick  it seems work now, I will update here if issue popup again during work.
