### ISSUE TITLE
Search form Issue

### ISSUE THREAD

**Issue by vprakashakeans** [lukechadwick/Liquify#47]
I'm using this extension for using Shopify editor in a while. Since I'm facing an issue with Search form this week, whereas the form not displays properly, that has the problem with form text visibility. 

![image](https://github.com/lukechadwick/Liquify/assets/126316001/c693f243-0626-463b-9807-69f99acd85fb)

It will be helpful if anyone find and fix the above issue ASAP..

**Comment by nemecky** [comment]
I'm actually having that issue, too. I also have to hard refresh several times in order to get the enhanced search to even work, but then when it does I get this search bar where you can't see whatever you type.

**Comment by kayteetrudeau** [comment]
This suddenly happened to me. I see it's closed, but what is the fix?

**Comment by nemecky** [comment]
Yes this is now happening to me again as of a few days ago. I thought I needed to update Chrome but I just did that and it's still showing the "collapsed" search field and whatever you type is not displayed.

**Comment by seanhopkins** [comment]
Issue is happening for me as well
