### ISSUE TITLE
Search field "collapsed" and text is not visible

### ISSUE THREAD

**Issue by nemecky** [lukechadwick/Liquify#48]
As the title indicates, the recent issue where the search field collapses after the "enhanced search loading" is finished has returned. (see Issue #47) ...whatever I type there is not visible

![image](https://github.com/user-attachments/assets/7f06ee06-750e-4c0c-82a2-6ce6b87cdf98)

**Comment by sp-hy** [comment]
I've released a new version which should be available soon
