### ISSUE TITLE
Enhanced search does not work

### ISSUE THREAD

**Issue by husseiny-alyasra** [lukechadwick/Liquify#7]
I don't believe the Enhanced search is working properly, like i enter the search term but nothing happens.

**Comment by lukechadwick** [comment]
Could you see if the issue persists on a clean install of a Shopify theme like Dawn/Debut?

**Comment by husseiny-alyasra** [comment]
it works yes with a clean install

**Comment by lukechadwick** [comment]
Hmm perhaps it's something in the theme code tripping up the extension, would you be willing to send me a copy of the theme so I can try it on my test store?

**Comment by husseiny-alyasra** [comment]
unfortunately that won't be possible, since I don't actually own the theme myself, but it belongs to the company I work for :(

**Comment by husseiny-alyasra** [comment]
i understand it would be tough to debug the issue without having access to the code, but your effort and response is much appreciated. like the extension works perfectly aside from the search and honestly with the search it would have been too good to be true.

so thank you!

**Comment by lukechadwick** [comment]
No worries, I have an idea of what the issue is. I will try add a fix and see if it helps

**Comment by husseiny-alyasra** [comment]
I would greatly appreciate it

**Comment by lukechadwick** [comment]
No problem. So each file in the theme should return a json object 
![image](https://user-images.githubusercontent.com/6725655/157649356-595e6e14-f1f3-4cce-833b-572fff12f415.png)

I'd assumed that each asset should contain the "value" key which contains the content of the file that I search through. I suspect one of the files in your theme is missing the value key, so it broke the search code. I've added a check to make sure this key is present before searching.  If it's missing it will log the result to the console so if you could let me know which file it is that fails I'd appreciate it as I'm kinda curious lol.

I've added this to the chrome store but it make take a day or so before it's reviewed, but you can also pull down/DL this repo and load it as an unpacked extension to test.

**Comment by husseiny-alyasra** [comment]
hey man,

sorry for the late reply.
are adding them into an array and printing it to the console?

**Comment by lukechadwick** [comment]
re:  https://github.com/lukechadwick/Liquify/commit/263559af3dcf0022d0d4cfc2a4212171cfd6383a

There should be one log that prints out an array of all assets, if any of them are missing the value property it will make another log prefixed by 'asset failed'.

Are you still seeing any errors?

**Comment by husseiny-alyasra** [comment]
I'm actually not getting any errors any more and the search is working.
the weird thing is that no files are printed with the failed-asset prefix.  which means that all files follow the proper format.

**Comment by lukechadwick** [comment]
Weird, maybe it was just a temporary issue, at least there's a condition in the code to handle it if it happens again.

**Comment by husseiny-alyasra** [comment]
yes maybe, thanks a lot for your efforts. much appreciated 🙏

**Comment by lukechadwick** [comment]
No problem, feel free to leave a chrome store review if you like the extension.
